version: '2'

volumes:
  db-volume:

networks:
  web:
  fila:
  db:

services:
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app

  app:
    image: python:3.6
    env_file:
      - ./.env
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    depends_on:
      - db
    networks:
      - web
      - fila
      - db

  db:
    build: db
    env_file:
      - ./.env
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - 6033:3306
    networks:
      - db

  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
      - app

  queue:
    image: redis:3.2
    networks:
      - fila